# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '2.1'

# Define services
services:

  # Database Service (Mysql)
  db:
    container_name: bank-db
    image: 'mysql/mysql-server:5.7'
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bank_transaction
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3301:3306'
    restart: always

  # App backend service
  app-server:
    # Configuration for building the docker image for the spring boot mvc
    image: bank-spring-boot-app
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - 8091:8090
    volumes:
      - /data/bank-spring-boot-app
    depends_on:
      db:
        condition: service_healthy