version: '3.7'

services:
  spring-boot-app:
    image: bank-transactions
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    restart:
      unless-stopped
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8091:8090"
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

# Volumes
volumes:
  db-data: