version: "3"

services:
  service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bank-service-app
    restart: on-failure
    ports:
      - "8091:8090"
    networks:
      - banknet
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb/bank?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_DATASOURCE_PLATFORM=mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    container_name: bank-service-mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - banknet
    environment:
      - MYSQL_ROOT_HOST='%'
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bank
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 20s
      retries: 10

networks:
  banknet:
    driver: bridge
