version: '2.1'

services:
  app-main:
    image: app-main-image
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8090:8090
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=neovision
      - DATABASE_NAME=bank_transaction
      - DATABASE_PORT=33061
    restart: always
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=neovision
      - MYSQL_DATABASE=bank_transaction
      - MYSQL_USER=root
      - MYSQL_PASSWORD=neovision
    ports:
      - 33061:3306
    volumes:
      - ./data/:/var/lib/mysql
    restart: always
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=neovision 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }