#spring:
#  ## Spring DATA SOURCE Configurations
#  datasource:
#    url: jdbc:mysql://localhost:3306/bank_transaction?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: ENC(LTXFhqlXnfBYyGPUkinQ/w==)

#Admin app admin user credentials
root:
  email: admin.bank_transaction@neovision.am
  #root_123456
  password: ENC(8AktOy1Shya0wo4CPET0+hjQ5s6FLycx)

jasypt:
  encryptor:
    password: neovision_secret
