#spring:
#  # Spring DATA SOURCE Configurations
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}

#Admin app admin user credentials
root:
  email: admin.bank_transaction@neovision.am
  #root_123456
  password: ENC(8AktOy1Shya0wo4CPET0+hjQ5s6FLycx)

jasypt:
  encryptor:
    password: neovision_secret
