spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/${DB_DATABASE:bank_transaction}?useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
#Admin app admin user credentials
root:
  email: admin.bank_transaction@neovision.am
  password: ENC(HIxhyytc9QoyOLKj+25p/A==)

jasypt:
  encryptor:
    password: secret