spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_DATABASE:bank_transaction}?useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

#Admin app admin user credentials
root:
  email: admin.bank_transaction@neovision.am
  #root_123456
  password: ENC(8AktOy1Shya0wo4CPET0+hjQ5s6FLycx)

jasypt:
  encryptor:
    password: neovision_secret