spring:
  datasource:
    url: jdbc:msyql://${DB_HOST:localhost}:3306/${DB_DATABASE:bank_transaction}?useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
#Admin app admin user credentials
root:
  email: root.mongoadmin@polixis.com
  password: ENC(Mj3KG0Sy88eEmxcgxUUflByvsFSz8Hn+)

jasypt:
  encryptor:
    password: secret
