SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

INSERT INTO ACCOUNT(UUID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, CREATED_DATE)
VALUES('abcd1234', 'hakobhn@gmail.com', '$2a$10$z4VuHA5jnC5YL9UPzzh/KeR3YHLxXQNi6CCj.Jz5CXRo.6tixNjzC', 'Rajeev', 'Singh', '2020-01-01');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;