SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

/*[22-Dec 8:49:20 PM][2 ms]*/ INSERT INTO `bank_transaction`.`currency_rate` (`CURRENCY`, `RATE`, `CREATED_DATE`) VALUES ('EURO', '630.5', '2020-12-22 20:49:15');
/*[22-Dec 8:49:37 PM][2 ms]*/ INSERT INTO `bank_transaction`.`currency_rate` (`CURRENCY`, `RATE`, `CREATED_DATE`) VALUES ('GBP', '712', '2020-12-22 20:49:35');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;